### ISSUE TITLE
Cut-n-paste error (?) in jamFile.js

### ISSUE THREAD

**Issue by DirkReiners** [tiesselune/git-jam#6]
I think I found a minor error in jamFile.js while trying to use it with SourceTree:

``` javascript
diff --git a/modules/jamFile.js b/modules/jamFile.js
index 2cc7b8e..b9468ad 100644
--- a/modules/jamFile.js
+++ b/modules/jamFile.js
@@ -65,7 +65,7 @@ exports.getDigestFromJam = function(arg){
                return exports.getDigestFromJamPath(arg);
        }
        if(arg instanceof Buffer){
-               return exports.getDigestFromJamData(data);
+               return exports.getDigestFromJamData(arg);
        }
        return "";
 }
```

It seems to run now. It's not doing anything sensible yet, but that's a different story...

Thanks!

**Comment by tiesselune** [comment]
I just merged your pull request: https://github.com/tiesselune/git-jam/commit/54b7780e4cca2108e07ded491a5ba83209b0dc3c This bug should be resolved now. :smiley: I'm closing the issue.
