### ISSUE TITLE
Configurable ssh key name

### ISSUE THREAD

**Issue by DirkReiners** [tiesselune/git-jam#7]
It would be very helpful if there was a config option to define which ssh key to use, as there typically are several, and they're not all named id_rsa. ;)

**Comment by tiesselune** [comment]
Indeed; it sounds fair. It's fairly easy to implement new config options using the `gitUtils.jamConfig` method so it should not be too much of a hassle. I'll look into it soon :wink:

**Comment by tiesselune** [comment]
Ok, I've made the really small change to allow that but could not test it yet : Here's the commit : https://github.com/tiesselune/git-jam/commit/2530c25032ce858882bff986fb36d2af8c5529ae
It's on another branch for now, until I can test it. :wink:

**Comment by tiesselune** [comment]
Git-jam is now configured to use SSH Agent if `SSH_AUTH_SOCK` environment variable is set. Integrated in commit https://github.com/tiesselune/git-jam/commit/eb749f04fab9429aa067d683f83e159516a7e336 thanks to @DirkReiners.
